### ISSUE TITLE
Create CLI tool for genereting report

### ISSUE THREAD

**Issue by mihaibivol** [mihaibivol/Graphite-Anomaly-Detector#3]
# Deliverables

CLI tool that generates a report and saves a csv with needed data
Desired usage
./generate_report hosts [params]

params:
-l=limit: Limit data request count per host to parameter. Default: 500
-p=pattern: Generate reports for metrics that match glob pattern. Default: all
-t=timeout: Timeout bethween requests on the same host. Default: 1 second
-o=filename: Output file
-u: Upload csv to Google Drive with the credentials specified in config.py
# TODO:
- [x] Implement commandline arguments
- [x] Get all metrics from hosts that match pattern
- [x] Implement limit per host
- [x] Retrieve timeseries for host
- [x] Test with dummy detector class
- [x] Implement output file
- [ ] ~~Implement upload to Drive~~
