### ISSUE TITLE
Add heuristics to SpikeDetector

### ISSUE THREAD

**Issue by mihaibivol** [mihaibivol/Graphite-Anomaly-Detector#4]
# Deliverables

A spike detector that yields tuples (timestamp, priority) where priority is a float bethween 0 and 1 meaning the priority of the spike.
# TODO
- [x] Retrieve spikes that are really high but were smoothed
- [x] Determine a priority for spikes that were smoothed
- [x] Determine spikes on smoothed series
- [x] Make sure that no duplicate spikes are found
